import { useState, useEffect } from "react";

// Supported languages
export type Language = "en" | "es" | "fr" | "de" | "zh";

// Translations object structure
type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

// Default translations
const translations: Translations = {
  en: {
    appName: "LibraryLens AI",
    bookAnalysis: "Book Analysis",
    bookArchive: "Book Archive",
    batchProcessing: "Batch Processing",
    settings: "Settings",
    recentBooks: "Recent Books",
    uploadCover: "Upload Book Cover",
    uploadFile: "Upload a file",
    dragDrop: "or drag and drop",
    enterDetails: "Or enter book details manually",
    title: "Title",
    author: "Author",
    isbn: "ISBN",
    analyzeBook: "Analyze Book",
    analysisOptions: "Analysis Options",
    generateSummary: "Generate Summary",
    summaryDesc: "Creates a concise summary of the book's content",
    identifyGenres: "Identify Genres",
    genresDesc: "Detects primary and secondary genres",
    extractThemes: "Extract Themes",
    themesDesc: "Identifies major themes and motifs",
    assessReadingLevel: "Assess Reading Level",
    readingLevelDesc: "Determines appropriate age/grade level",
    generateCatalog: "Generate Catalog Entry",
    catalogDesc: "Creates a formatted catalog entry",
    results: "Book Analysis Results",
    insights: "AI-powered insights and classification",
    complete: "Complete",
    processing: "Processing",
    publisher: "Publisher",
    published: "Published",
    pages: "Pages",
    genres: "Genres",
    readingLevel: "Reading Level",
    aiSummary: "AI-Generated Summary",
    majorThemes: "Major Themes",
    catalogEntry: "Library Catalog Entry",
    similarBooks: "Similar Books",
    exportResults: "Export Results",
    saveToArchive: "Save to Archive",
    searching: "Searching...",
    noResults: "No results found",
    error: "An error occurred",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    confirm: "Confirm",
    search: "Search",
    clear: "Clear",
    loading: "Loading...",
  },
  es: {
    appName: "LibraryLens AI",
    bookAnalysis: "Análisis de Libros",
    bookArchive: "Archivo de Libros",
    batchProcessing: "Procesamiento por Lotes",
    settings: "Configuración",
    recentBooks: "Libros Recientes",
    uploadCover: "Subir Portada del Libro",
    uploadFile: "Subir un archivo",
    dragDrop: "o arrastrar y soltar",
    enterDetails: "O ingrese los detalles del libro manualmente",
    title: "Título",
    author: "Autor",
    isbn: "ISBN",
    analyzeBook: "Analizar Libro",
    analysisOptions: "Opciones de Análisis",
    generateSummary: "Generar Resumen",
    summaryDesc: "Crea un resumen conciso del contenido del libro",
    identifyGenres: "Identificar Géneros",
    genresDesc: "Detecta géneros primarios y secundarios",
    extractThemes: "Extraer Temas",
    themesDesc: "Identifica temas y motivos principales",
    assessReadingLevel: "Evaluar Nivel de Lectura",
    readingLevelDesc: "Determina el nivel de edad/grado apropiado",
    generateCatalog: "Generar Entrada de Catálogo",
    catalogDesc: "Crea una entrada de catálogo formateada",
    results: "Resultados del Análisis del Libro",
    insights: "Información y clasificación con IA",
    complete: "Completo",
    processing: "Procesando",
    publisher: "Editorial",
    published: "Publicado",
    pages: "Páginas",
    genres: "Géneros",
    readingLevel: "Nivel de Lectura",
    aiSummary: "Resumen Generado por IA",
    majorThemes: "Temas Principales",
    catalogEntry: "Entrada de Catálogo de Biblioteca",
    similarBooks: "Libros Similares",
    exportResults: "Exportar Resultados",
    saveToArchive: "Guardar en Archivo",
    searching: "Buscando...",
    noResults: "No se encontraron resultados",
    error: "Ocurrió un error",
    cancel: "Cancelar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    confirm: "Confirmar",
    search: "Buscar",
    clear: "Limpiar",
    loading: "Cargando...",
  },
  fr: {
    appName: "LibraryLens AI",
    bookAnalysis: "Analyse de Livres",
    bookArchive: "Archives de Livres",
    batchProcessing: "Traitement par Lots",
    settings: "Paramètres",
    recentBooks: "Livres Récents",
    uploadCover: "Télécharger la Couverture",
    uploadFile: "Télécharger un fichier",
    dragDrop: "ou glisser-déposer",
    enterDetails: "Ou entrez les détails du livre manuellement",
    title: "Titre",
    author: "Auteur",
    isbn: "ISBN",
    analyzeBook: "Analyser le Livre",
    analysisOptions: "Options d'Analyse",
    generateSummary: "Générer un Résumé",
    summaryDesc: "Crée un résumé concis du contenu du livre",
    identifyGenres: "Identifier les Genres",
    genresDesc: "Détecte les genres primaires et secondaires",
    extractThemes: "Extraire les Thèmes",
    themesDesc: "Identifie les thèmes et motifs majeurs",
    assessReadingLevel: "Évaluer le Niveau de Lecture",
    readingLevelDesc: "Détermine le niveau d'âge/grade approprié",
    generateCatalog: "Générer une Entrée de Catalogue",
    catalogDesc: "Crée une entrée de catalogue formatée",
    results: "Résultats de l'Analyse du Livre",
    insights: "Informations et classification par IA",
    complete: "Terminé",
    processing: "En traitement",
    publisher: "Éditeur",
    published: "Publié",
    pages: "Pages",
    genres: "Genres",
    readingLevel: "Niveau de Lecture",
    aiSummary: "Résumé Généré par IA",
    majorThemes: "Thèmes Principaux",
    catalogEntry: "Entrée de Catalogue de Bibliothèque",
    similarBooks: "Livres Similaires",
    exportResults: "Exporter les Résultats",
    saveToArchive: "Enregistrer dans les Archives",
    searching: "Recherche en cours...",
    noResults: "Aucun résultat trouvé",
    error: "Une erreur est survenue",
    cancel: "Annuler",
    save: "Enregistrer",
    delete: "Supprimer",
    edit: "Modifier",
    confirm: "Confirmer",
    search: "Rechercher",
    clear: "Effacer",
    loading: "Chargement...",
  },
  de: {
    appName: "LibraryLens AI",
    bookAnalysis: "Buchanalyse",
    bookArchive: "Bucharchiv",
    batchProcessing: "Stapelverarbeitung",
    settings: "Einstellungen",
    recentBooks: "Neueste Bücher",
    uploadCover: "Buchcover hochladen",
    uploadFile: "Datei hochladen",
    dragDrop: "oder ziehen und ablegen",
    enterDetails: "Oder geben Sie die Buchdetails manuell ein",
    title: "Titel",
    author: "Autor",
    isbn: "ISBN",
    analyzeBook: "Buch analysieren",
    analysisOptions: "Analyseoptionen",
    generateSummary: "Zusammenfassung erstellen",
    summaryDesc: "Erstellt eine prägnante Zusammenfassung des Buchinhalts",
    identifyGenres: "Genres identifizieren",
    genresDesc: "Erkennt primäre und sekundäre Genres",
    extractThemes: "Themen extrahieren",
    themesDesc: "Identifiziert Hauptthemen und Motive",
    assessReadingLevel: "Leseniveau bewerten",
    readingLevelDesc: "Bestimmt das angemessene Alters-/Klassenniveau",
    generateCatalog: "Katalogeintrag erstellen",
    catalogDesc: "Erstellt einen formatierten Katalogeintrag",
    results: "Buchanalyse-Ergebnisse",
    insights: "KI-gestützte Erkenntnisse und Klassifizierung",
    complete: "Abgeschlossen",
    processing: "Verarbeitung",
    publisher: "Verlag",
    published: "Veröffentlicht",
    pages: "Seiten",
    genres: "Genres",
    readingLevel: "Leseniveau",
    aiSummary: "KI-generierte Zusammenfassung",
    majorThemes: "Hauptthemen",
    catalogEntry: "Bibliothekskatalog-Eintrag",
    similarBooks: "Ähnliche Bücher",
    exportResults: "Ergebnisse exportieren",
    saveToArchive: "Im Archiv speichern",
    searching: "Suche...",
    noResults: "Keine Ergebnisse gefunden",
    error: "Ein Fehler ist aufgetreten",
    cancel: "Abbrechen",
    save: "Speichern",
    delete: "Löschen",
    edit: "Bearbeiten",
    confirm: "Bestätigen",
    search: "Suchen",
    clear: "Löschen",
    loading: "Laden...",
  },
  zh: {
    appName: "LibraryLens AI",
    bookAnalysis: "图书分析",
    bookArchive: "图书档案",
    batchProcessing: "批量处理",
    settings: "设置",
    recentBooks: "最近的书籍",
    uploadCover: "上传书籍封面",
    uploadFile: "上传文件",
    dragDrop: "或拖放",
    enterDetails: "或手动输入书籍详情",
    title: "标题",
    author: "作者",
    isbn: "ISBN",
    analyzeBook: "分析书籍",
    analysisOptions: "分析选项",
    generateSummary: "生成摘要",
    summaryDesc: "创建书籍内容的简明摘要",
    identifyGenres: "识别类型",
    genresDesc: "检测主要和次要类型",
    extractThemes: "提取主题",
    themesDesc: "识别主要主题和motifs",
    assessReadingLevel: "评估阅读水平",
    readingLevelDesc: "确定适当的年龄/年级水平",
    generateCatalog: "生成目录条目",
    catalogDesc: "创建格式化的目录条目",
    results: "图书分析结果",
    insights: "AI驱动的洞察和分类",
    complete: "完成",
    processing: "处理中",
    publisher: "出版商",
    published: "出版日期",
    pages: "页数",
    genres: "类型",
    readingLevel: "阅读水平",
    aiSummary: "AI生成的摘要",
    majorThemes: "主要主题",
    catalogEntry: "图书馆目录条目",
    similarBooks: "类似书籍",
    exportResults: "导出结果",
    saveToArchive: "保存到档案",
    searching: "搜索中...",
    noResults: "未找到结果",
    error: "发生错误",
    cancel: "取消",
    save: "保存",
    delete: "删除",
    edit: "编辑",
    confirm: "确认",
    search: "搜索",
    clear: "清除",
    loading: "加载中...",
  }
};

export function useLanguage() {
  const [language, setLanguage] = useState<Language>("en");
  
  // Function to change the current language
  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("preferredLanguage", lang);
  };
  
  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key;
  };
  
  // Load saved language preference on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("preferredLanguage") as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);
  
  return { language, changeLanguage, t };
}
