import type { Express, Request, Response } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import multer from "multer";
import { z } from "zod";
import { bookAnalysisSchema, Book, InsertBook } from "@shared/schema";
import { processBookAnalysis, analyzeBookCover } from "./services/openai";
import { enrichBookMetadata, searchBooks, getBookByISBN, searchSimilarBooks } from "./services/googleBooks";

// Set up multer for in-memory file storage
const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: 10 * 1024 * 1024, // 10MB limit
  },
});

export async function registerRoutes(app: Express): Promise<Server> {
  // Create server
  const httpServer = createServer(app);

  // API Endpoints - prefix all with /api
  
  // Book Analysis endpoints
  app.post("/api/books/analyze", upload.single("coverImage"), async (req: Request, res: Response) => {
    try {
      // Parse and validate request data
      let bookInfo: any = {};
      
      if (req.body) {
        const bodyData = typeof req.body === "string" ? JSON.parse(req.body) : req.body;
        bookInfo = {
          ...bodyData,
          options: bodyData.options ? 
            (typeof bodyData.options === 'string' ? JSON.parse(bodyData.options) : bodyData.options) 
            : undefined
        };
      }
      
      // If coverImage is uploaded, store it
      if (req.file) {
        const imageBase64 = req.file.buffer.toString("base64");
        bookInfo.coverImageData = `data:${req.file.mimetype};base64,${imageBase64}`;
      }
      
      // For this minimal version, we'll create a simple analysis without API calls
      // In a production version, these would call the OpenAI and Google Books APIs
      const analysisResult = {
        title: bookInfo.title || "Unknown Title",
        author: bookInfo.author || "Unknown Author",
        isbn: bookInfo.isbn || "",
        coverImageUrl: bookInfo.coverImageData || "",
        publisher: bookInfo.publisher || "",
        publishedYear: bookInfo.publishedYear || null,
        pageCount: bookInfo.pageCount || null,
        summary: "This is a placeholder summary for the book. In the full version, this would be generated by OpenAI.",
        genres: ["Fiction"],
        themes: ["Literature"],
        readingLevel: "General",
        deweyDecimal: "800",
        catalogEntry: `TITLE: ${bookInfo.title || "Unknown Title"}\nAUTHOR: ${bookInfo.author || "Unknown Author"}\nCLASSIFICATION: 800`,
        userId: bookInfo.userId || null,
      };
      
      // Store the book in the database
      const savedBook = await storage.createBook(analysisResult as InsertBook);
      
      res.status(200).json(savedBook);
    } catch (error) {
      console.error("Book analysis error:", error);
      res.status(500).json({ message: `Error analyzing book: ${error.message}` });
    }
  });

  // Book CRUD operations
  
  // GET /api/books - Get all books
  app.get("/api/books", async (req: Request, res: Response) => {
    try {
      const userId = req.query.userId ? parseInt(req.query.userId as string) : undefined;
      const books = await storage.getBooks(userId);
      res.status(200).json(books);
    } catch (error) {
      res.status(500).json({ message: `Error fetching books: ${error.message}` });
    }
  });
  
  // GET /api/books/recent - Get recent books
  app.get("/api/books/recent", async (req: Request, res: Response) => {
    try {
      const limit = req.query.limit ? parseInt(req.query.limit as string) : 5;
      const books = await storage.getRecentBooks(limit);
      res.status(200).json(books);
    } catch (error) {
      res.status(500).json({ message: `Error fetching recent books: ${error.message}` });
    }
  });
  
  // GET /api/books/search - Search books
  app.get("/api/books/search", async (req: Request, res: Response) => {
    try {
      const query = req.query.q as string;
      if (!query) {
        return res.status(400).json({ message: "Search query is required" });
      }
      
      const books = await storage.searchBooks(query);
      res.status(200).json(books);
    } catch (error) {
      res.status(500).json({ message: `Error searching books: ${error.message}` });
    }
  });
  
  // GET /api/books/:id - Get a specific book
  app.get("/api/books/:id", async (req: Request, res: Response) => {
    try {
      const id = parseInt(req.params.id);
      const book = await storage.getBook(id);
      
      if (!book) {
        return res.status(404).json({ message: "Book not found" });
      }
      
      res.status(200).json(book);
    } catch (error) {
      res.status(500).json({ message: `Error fetching book: ${error.message}` });
    }
  });
  
  // POST /api/books - Create a new book
  app.post("/api/books", async (req: Request, res: Response) => {
    try {
      // Create book with validated data
      const bookData: InsertBook = req.body;
      const newBook = await storage.createBook(bookData);
      
      res.status(201).json(newBook);
    } catch (error) {
      res.status(500).json({ message: `Error creating book: ${error.message}` });
    }
  });
  
  // PUT /api/books/:id - Update a book
  app.put("/api/books/:id", async (req: Request, res: Response) => {
    try {
      const id = parseInt(req.params.id);
      const bookData: Partial<InsertBook> = req.body;
      
      const updatedBook = await storage.updateBook(id, bookData);
      
      if (!updatedBook) {
        return res.status(404).json({ message: "Book not found" });
      }
      
      res.status(200).json(updatedBook);
    } catch (error) {
      res.status(500).json({ message: `Error updating book: ${error.message}` });
    }
  });
  
  // DELETE /api/books/:id - Delete a book
  app.delete("/api/books/:id", async (req: Request, res: Response) => {
    try {
      const id = parseInt(req.params.id);
      const success = await storage.deleteBook(id);
      
      if (!success) {
        return res.status(404).json({ message: "Book not found" });
      }
      
      res.status(204).send();
    } catch (error) {
      res.status(500).json({ message: `Error deleting book: ${error.message}` });
    }
  });

  // Batch processing endpoint
  app.post("/api/books/batch", upload.array("coverImages", 10), async (req: Request, res: Response) => {
    try {
      const files = req.files as Express.Multer.File[];
      
      if (!files || files.length === 0) {
        return res.status(400).json({ message: "No files were uploaded" });
      }
      
      // Process each image and apply book analysis
      const results = [];
      const processed = { success: 0, failed: 0 };
      
      for (const file of files) {
        try {
          // Convert image to base64
          const imageBase64 = file.buffer.toString("base64");
          const coverImageData = `data:${file.mimetype};base64,${imageBase64}`;
          
          // For minimal version - create placeholder book for each file
          const bookTitle = file.originalname.replace(/\.\w+$/, "").replace(/[-_]/g, " ");
          
          // Create a simple book entry without API calls
          const bookData = {
            title: bookTitle,
            author: "Unknown Author",
            isbn: "",
            coverImageUrl: coverImageData,
            publisher: "",
            publishedYear: null,
            pageCount: null,
            summary: "This is a placeholder summary for the batch-uploaded book.",
            genres: ["Fiction"],
            themes: ["Literature"],
            readingLevel: "General",
            deweyDecimal: "800",
            catalogEntry: `TITLE: ${bookTitle}\nAUTHOR: Unknown\nCLASSIFICATION: 800`,
            userId: null,
          };
          
          // Save to storage
          const savedBook = await storage.createBook(bookData as InsertBook);
          
          results.push({
            filename: file.originalname,
            status: "success",
            book: savedBook
          });
          processed.success++;
        } catch (err) {
          results.push({
            filename: file.originalname,
            status: "error",
            error: err.message
          });
          processed.failed++;
        }
      }
      
      res.status(200).json({
        message: `Processed ${processed.success} books successfully, ${processed.failed} failed`,
        processed,
        results
      });
    } catch (error) {
      res.status(500).json({ message: `Error processing batch: ${error.message}` });
    }
  });

  // Google Books API integration endpoints - Simplified for minimal version
  
  // GET /api/googlebooks/search - Search books via Google Books API
  app.get("/api/googlebooks/search", async (req: Request, res: Response) => {
    try {
      // For minimal version, return sample books without API call
      const sampleBooks = [
        {
          id: "1",
          title: "To Kill a Mockingbird",
          author: "Harper Lee",
          publishedYear: 1960,
          coverImageUrl: "https://covers.openlibrary.org/b/id/7222665-L.jpg"
        },
        {
          id: "2",
          title: "The Great Gatsby",
          author: "F. Scott Fitzgerald",
          publishedYear: 1925,
          coverImageUrl: "https://covers.openlibrary.org/b/id/6883215-L.jpg"
        },
        {
          id: "3",
          title: "1984",
          author: "George Orwell",
          publishedYear: 1949,
          coverImageUrl: "https://covers.openlibrary.org/b/id/7222250-L.jpg"
        }
      ];
      
      res.status(200).json(sampleBooks);
    } catch (error: any) {
      res.status(500).json({ message: `Error searching Google Books: ${error.message}` });
    }
  });
  
  // GET /api/googlebooks/isbn/:isbn - Get book by ISBN
  app.get("/api/googlebooks/isbn/:isbn", async (req: Request, res: Response) => {
    try {
      const isbn = req.params.isbn;
      
      if (!isbn) {
        return res.status(400).json({ message: "ISBN is required" });
      }
      
      // For minimal version, return a sample book that matches the ISBN
      const sampleBook = {
        id: "isbn-" + isbn,
        title: "Sample Book for ISBN " + isbn,
        author: "Sample Author",
        publishedYear: 2020,
        isbn: isbn,
        coverImageUrl: "https://covers.openlibrary.org/b/isbn/" + isbn + "-L.jpg",
        description: "This is a sample book description for the minimal version."
      };
      
      res.status(200).json(sampleBook);
    } catch (error: any) {
      res.status(500).json({ message: `Error fetching book by ISBN: ${error.message}` });
    }
  });
  
  // POST /api/googlebooks/similar - Get similar books
  app.post("/api/googlebooks/similar", async (req: Request, res: Response) => {
    try {
      const bookInfo = req.body;
      
      if (!bookInfo || (!bookInfo.title && !bookInfo.author && !bookInfo.genres)) {
        return res.status(400).json({ message: "Book information is required (title, author, or genres)" });
      }
      
      // For minimal version, return sample similar books
      const similarBooks = [
        {
          id: "s1",
          title: "Similar Book 1",
          author: "Author 1",
          publishedYear: 2015,
          coverImageUrl: "https://covers.openlibrary.org/b/id/8231434-L.jpg"
        },
        {
          id: "s2",
          title: "Similar Book 2",
          author: "Author 2",
          publishedYear: 2018,
          coverImageUrl: "https://covers.openlibrary.org/b/id/12645114-L.jpg"
        }
      ];
      
      res.status(200).json(similarBooks);
    } catch (error: any) {
      res.status(500).json({ message: `Error finding similar books: ${error.message}` });
    }
  });

  return httpServer;
}
